Add replayable.io to readme
jyguyomarch/awesome-productivity pull request #107
Opened 2022-09-27 17:09 UTC by ianjennings

2022-11-19 20:36 UTC, jyguyomarch requested changes
Different or new section needed.

2022-11-19 20:36 UTC, jyguyomarch commented on README.md
> +- [Replayable](https://replayable.io) - Dashcam for desktop. Remember everything that happens on your desktop.
@ianjennings that's an interesting tool. I think it fits in the list but maybe not the Knowledge Management section. Maybe in the Misc, or maybe we need to start a new Screen Capture section. What do you think?

2022-11-21 19:37 UTC, ianjennings reviewed
Turn Misc into "screen capture" section

2022-11-21 19:38 UTC, ianjennings commented on README.md
> +- [Replayable](https://replayable.io) - Dashcam for desktop. Remember everything that happens on your desktop.
I turned the Misc section into "screen capture" since ShareX is also screen capture.

2022-11-22 15:10 UTC, jyguyomarch commented on README.md
> +- [Replayable](https://replayable.io) - Dashcam for desktop. Remember everything that happens on your desktop.
Good idea thx

2022-11-22 15:11 UTC, merged