Add Tinido
jyguyomarch/awesome-productivity pull request #85
Opened 2021-03-26 07:26 UTC by quangctkm9207

Add Tinido to Task Management Tool section.

2021-03-26 22:36 UTC, jyguyomarch requested changes
Small changes proposed

2021-03-26 22:36 UTC, jyguyomarch commented on README.md
> +- [ShareX](https://getsharex.com/) – Screen capture, file sharing and productivity tool.
Why this change? Just a different EOF? Maybe simply revert it

2021-03-26 22:36 UTC, jyguyomarch commented on README.md
> +- [Tinido](https://tinido.com/) - A beautiful task manager app showing your activity as GitHub contribution calendar.
Would suggest to rework the text. Something like "A beautiful and simple task management app that can also give you insights by showing your completed tasks in a contribution graph similar to the one you find on your GitHub profile."

2021-03-26 22:36 UTC, jyguyomarch commented on README.md
> +- [Tinido](https://tinido.com/) - A beautiful task manager app showing your activity as GitHub contribution calendar.
Use a em dash instead of a normal one

2021-03-27 12:21 UTC, quangctkm9207 commented on README.md
> +- [Tinido](https://tinido.com/) - A beautiful task manager app showing your activity as GitHub contribution calendar.
Thanks for suggestion

2021-03-27 12:21 UTC, quangctkm9207 commented on README.md
> +- [Tinido](https://tinido.com/) - A beautiful task manager app showing your activity as GitHub contribution calendar.
Got it.

2021-03-27 12:22 UTC, quangctkm9207 commented on README.md
> +- [ShareX](https://getsharex.com/) – Screen capture, file sharing and productivity tool.
I edited the README file directly via GitHub page (on browser).

2021-03-27 12:22 UTC, quangctkm9207 commented on README.md
> +- [ShareX](https://getsharex.com/) – Screen capture, file sharing and productivity tool.
Sorry for this mess.

2021-03-27 20:03 UTC, jyguyomarch commented on README.md
> +- [Tinido](https://tinido.com/) - A beautiful task manager app showing your activity as GitHub contribution calendar.
👍

2021-03-27 20:03 UTC, jyguyomarch approved these changes
👍

2021-03-27 20:03 UTC, merged